// Writes mobile/www/app-config.js from the LUXWELD_APP_URL env var so the
// wrapper's target can be set repeatably (e.g. in CI).
//   LUXWELD_APP_URL=https://warranty.luxweld.com.au npm run set-app-url
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const url = (process.env.LUXWELD_APP_URL || '').trim();
const out = resolve(import.meta.dirname, '../mobile/www/app-config.js');

if (url && !/^https?:\/\/\S+/i.test(url)) {
  console.error(`Refusing to write: LUXWELD_APP_URL="${url}" is not a valid http(s) URL.`);
  process.exit(1);
}

const body =
  `// Generated by scripts/set-app-url.mjs. Set the LUXWELD_APP_URL env var and re-run.\n` +
  `window.LUXWELD_APP_URL = ${JSON.stringify(url)};\n`;

writeFileSync(out, body);
console.log(
  url
    ? `Wrote mobile/www/app-config.js -> ${url}`
    : 'Wrote mobile/www/app-config.js with an EMPTY url (shell will show the setup screen).'
);
